# Generated by Django 3.2.18 on 2023-05-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.TextField(default='4d4bda7e-9889-4af5-aaf9-5268d58744a1', primary_key=True, serialize=False)),
                ('user_id', models.TextField(default='91d4b471-5901-4263-80af-896859e717a8')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.TextField(default='f38dbed1-0018-452c-b81c-9837c85c4174'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.TextField(default='f8e42ec8-f6d1-4ff0-94cb-205909ba289e', primary_key=True, serialize=False),
        ),
    ]
